version: '3'

services:

  fastapi:
    build: .
    restart: always 
    env_file: 
      - config/fastapi.env
      - config/db.env
    volumes:
      - ./backend:/usr/src/app/backend
    networks:
      solar-stats:
        aliases:
          - solar-stats-fastapi
    ports:
      - 3000:3000
    depends_on:
      - postgres15
    container_name: fastapi

  postgres15:
    image: postgres:15-alpine
    restart: always 
    env_file:
      - config/db.env
    environment:
      PGDATA: /var/lib/postgresql/data/
    networks:
      solar-stats:
        aliases:
          - solar-stats-postgres15
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: postgres15

networks:
  solar-stats:

volumes:
  pgdata:
